package com.family.common.enums;

public enum PrivilegeEnum {
    PROFILE_VIEW, PROFILE_CREATE, PROFILE_EDIT, PROFILE_DELETE,
    TREE_VIEW, TREE_EDIT, TREE_EXPORT,
    EVENT_VIEW, EVENT_CREATE, EVENT_EDIT, EVENT_DELETE,
    POST_VIEW, POST_CREATE, POST_EDIT, POST_DELETE,
    GALLERY_VIEW, GALLERY_CREATE, GALLERY_EDIT, GALLERY_DELETE, GALLERY_UPLOAD,
    FUND_VIEW, FUND_MANAGE, FUND_TRANSACTION, FUND_REPORT,
    FILE_UPLOAD_PUBLIC, FILE_UPLOAD_PRIVATE, FILE_DELETE,
    USER_VIEW, USER_CREATE, USER_EDIT, USER_DELETE, USER_ROLE
}
